# Generated by Django 5.2.4 on 2025-07-18 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_department_individual_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.department'),
        ),
    ]
